os:
- linux
- osx
- windows
language: rust
cache:
  - cargo
  - directories:
      - $HOME/.rustup

rust:
- stable
- beta
- nightly
- 1.22.0

before_script:
  - if [ ${TRAVIS_RUST_VERSION} == "stable" ]; then
    rustup component add clippy-preview rustfmt;
    cargo fmt --all -- --check;
    cargo clippy -- -A clippy::cmp_owned -W clippy::all;
    fi

script:
- cargo build --verbose
- cargo test --verbose
- cargo run --verbose --example test
- cargo build --release


notifications:
  email:
    on_success: never
